provider "aws" {}

module "aws_modules" {
  prefix_name               = "demo"
  name                      = "nodejs-rest"
  source                    = "../../modules/aws_modules"
  region                    = "ap-southeast-1"
  vpc_cidr                  = "10.1.0.0/16"

  # Public key name generated by AWS.
  key_name                  = "<CHANGE_ME>"

  # Value of Base image builded by Packer.
  base_ami                  = "<CHANGE_ME>"

  app_instance_type         = "t2.micro"
  db_instance_type          = "t2.micro"

  # The 'demo-nodejs-mongodb-rest' image container version. Stored are DockerHub registry
  app_version               = "develop"
}

output "app_endpoint_ip" {
  # Endpoint to access
  value = "${module.aws_modules.app_public_ip}"
}
